version: '3.8'
services:
  gotobed:
    build:
      context: ..
      dockerfile: gotobed-system/Dockerfile
    container_name: gotobed-system
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
